config/routes.rb
Rails.application.routes.draw do


  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 # 管理者用
# URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get "about" => "homes#about", as: "about"
    resources :items, only:[:index,:show]

    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:show, :edit, :update]

    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only:[:index,:update,:create,:destroy]

    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only:[:new,:index,:show,:create]

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  namespace :admin do
    get "/" => 'homes#top'
    patch 'order_details/update'
    resources :orders, only: [:show, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :orders
  has_many :cart_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  def shipping_cost
    800
  end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid: 1, production: 2, shipping_preparation: 3, shipped: 4 }
  # { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.new
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    #@orders = Oder.all
    if @customer.update(customer_params)
      redirect_to admin_customers_path(@customer),notice: "User was successfully updated."
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name,:fast_name,:last_name_kana,
    :fast_name_kana,:email,:postal_code,:address,:telephone_number,:is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
  		redirect_to admin_genres_path(@genre.id), notice: "Genre was successfully created."
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre)
    else
      render :edit
    end
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

  private
  def order_params
    params.require(:order).permit(:id,:name,:status,:created_at,:updated_at)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item = Item.new
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
  		redirect_to admin_items_path(@item.id), notice: "商品が登録されました！"
    else
      @items = Item.all
      render :index
    end
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_items_path(@item)
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  private
  def item_params
    params.require(:item).permit(:id,:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   case resource
   when Admin
    root_path
   when Customer
    customer_path(current_customer.id)
   end
  end

  private


  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:last_name,:fast_name,
   :last_name_kana,:fast_name_kana,:postal_code,:address,:telephone_number,:is_deleted,
   :created_at,:updated_at])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/making_status_helper.rb
module Admin::MakingStatusHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/status_helper.rb
module Admin::StatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 col-auto">
      <h2><%= @customer.last_name + @customer.fast_name %>さんの会員情報編集</h2>
    </div>
  </div>

  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 mx-auto">

    <%= form_with model: @customer, local: true,url: admin_customer_path do |f| %>
     <div class="form-group">
       <%= f.label :"氏名", class: "label" %>
       <%= f.text_field :last_name, autofocus: true %>
       <%= f.text_field :fast_name, autofocus: true %>
     </div>
     <div class="form-group">
       <%= f.label :"フリガナ", class: "label" %>
       <%= f.text_field :last_name_kana %>
       <%= f.text_field :fast_name_kana %>
     </div>
     <div class="form-group">
       <%= f.label :postal_code,"郵便番号", class: "label" %>
       <%= f.text_field :postal_code %>
     </div>
     <div class="form-group">
       <%= f.label :address, "住所", class: "label" %>
       <%= f.text_field :address %>
     </div>
     <div class="form-group">
       <%= f.label :telephone_number, "電話番号", class: "label" %>
       <%= f.text_field :telephone_number %>
     </div>
     <div class="form-group">
       <%= f.label :email, "メールアドレス", class: "label" %>
       <%= f.text_field :email %>
     </div>

     <div class="form-group">
       <%= f.radio_button :is_deleted, :true %>
       <%= f.label :is_deleted, "有効" %>
       <%= f.radio_button :is_deleted, :false %>
       <%= f.label :is_deleted, "退会" %><br />
     </div>
      <%= f.submit "変更を保存" , class:'btn btn-sm btn-success' %>
    <% end %>

    </div>
 </div>

</div>

app/views/admin/customers/index.html.erb
<div class= "container">
  <div class = "row">
    <h2 class="title">会員一覧</h2>
  </div>
  <div class= "row">
   <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 mx-auto">
      <table class="table table-hover table-inverse">
       <thead class="table-light">
        <tr>
         <th>会員ID</th>
         <th>氏名</th>
         <th colpan="2"></th>
         <th>メールアドレス</th>
         <th colpan="2"></th>
         <th>ステータス</th>
        </tr>
       </thead>
       <tbody>
        <% @customers.each do |customer| %>
         <tr>
          <td><%= customer.id %></td>
          <td>
           <%= link_to admin_customer_path(customer.id) do %>
           <%= customer.last_name + customer.fast_name %>
           <% end %>
          </td>
          <td colpan="2"></td>
          <td><%= customer.email %></td>
          <td colpan="2"></td>
          <td><%= customer.is_deleted %></td>
         </tr>
        <% end %>
       </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class= "container">
  <div class = "row">
    <h2 class="title">
      会員詳細
    </h2>
  </div>

  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 mx-auto">
      <table class= "table">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name + @customer.fast_name %></td>
        </tr>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana + @customer.fast_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号<br></th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        </tr>
        <tr>
          <th>メールアドレス<br></th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <%#= form_with model: @item, local: true do |f| %>
          <td>
           <%= @customer.is_deleted %>
          </td>
          <%# end %>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_customer_path(@customer.id),class: "btn btn-sm btn-success" %>
    </div>
  </div>
</div>