config/routes.rb
Rails.application.routes.draw do


  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 # 管理者用
# URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get "about" => "homes#about", as: "about"
    resources :items, only:[:index,:show]

    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:show, :edit, :update]

    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only:[:index,:update,:create,:destroy]

    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only:[:new,:index,:show,:create]

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  namespace :admin do
    get "/" => 'homes#top'
    patch 'order_details/update'
    resources :orders, only: [:show, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :orders
  has_many :cart_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  def shipping_cost
    800
  end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid: 1, production: 2, shipping_preparation: 3, shipped: 4 }
  # { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
  		redirect_to admin_genres_path(@genre.id), notice: "Genre was successfully created."
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre)
    else
      render :edit
    end
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

  private
  def order_params
    params.require(:order).permit(:id,:name,:status,:created_at,:updated_at)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item = Item.new
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
  		redirect_to admin_items_path(@item.id), notice: "商品が登録されました！"
    else
      @items = Item.all
      render :index
    end
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_items_path(@item)
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  private
  def item_params
    params.require(:item).permit(:id,:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_detail = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    
    if @order.update(order_params)
      redirect_to admin_orders_show_path(@order),notice: "User was successfully updated."
    else
      render :show
    end
  end

  def order_params
    params.require(:order).permit(:id,:name,:address,:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   case resource
   when Admin
    root_path
   when Customer
    customer_path(current_customer.id)
   end
  end

  private


  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:last_name,:fast_name,
   :last_name_kana,:fast_name_kana,:postal_code,:address,:telephone_number,:is_deleted,
   :created_at,:updated_at])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/making_status_helper.rb
module Admin::MakingStatusHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/status_helper.rb
module Admin::StatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class= "container">
   <div class= "row">
     <h2 class="title">ジャンル編集</h2>
   </div>
   <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 col-auto">

       <div><%= form_with model: @genre,url: {controller: 'genres', action: 'update'} do |f| %>
              <%= f.label :"ジャンル名" %>
              <%= f.text_field :name, autofocus: true, :placeholder =>"#{@genre.name}" %>
              <%= f.submit "変更を保存" ,class:'btn btn-sm btn-success' %>
              <% end %>
       </div>
     </div>
    </div>

  </div>

app/views/admin/genres/index.html.erb
<div class= "container">
  <div class = "row">
    <h2 class="title">ジャンル一覧・追加</h2>
  </div>
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 col-auto">

      <%= form_with model: @genre,url: {controller: 'genres', action: 'create'} do |f| %>
      <div class="form-group">
        <%= f.label :"ジャンル名" %>
        <%= f.text_field :name ,placeholder:"ジャンル名"%>
        <%= f.submit "新規登録", class:'btn btn-sm btn-success' %>
      <% end %>
      </div>
    </div>
  </div>

  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 col-auto">
      <table class="table table-hover table-inverse">
       <thead class="table-light">
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
       </thead>
       <tbody>
        <% @genres.each do |genre| %>
             <tr>
              <td>
               <%= genre.name %>
              </td>
              <td>
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %>
              </td>
             </tr>
            <% end %>
       </tbody>
      </table>
    </div>
  </div>

app/views/admin/items/edit.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 col-auto">
      <h2>商品編集</h2>
    </div>
  </div>

  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 mx-auto">

    <%= form_with model: @item, local: true,url: admin_item_path do |f| %>
     <div class="form-group">
       <%= f.label :image, "商品画像", class: "label" %>
       <%= f.file_field :image, accept: "image/*" %>
     </div>
     <div class="form-group">
       <%= f.label :name, "商品名", class: "label" %>
       <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"商品名" %>
     </div>
     <div class="form-group">
       <%= f.label :introduction, "商品説明", class: "label" %>
       <%= f.text_area :introduction, id:"inputIntroduction", placeholder: "ここに説明文を表示します" %>
     </div>
     <div class="form-group">
       <%= f.label :genre_id,"ジャンル選択", class: "label" %>
       <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name)%>
       <%#= f.select :genre_id, [[@genre.name, 1], [@genre.name, 2,]], id:"genre_id",{include_blank: '--選択してください--'} %>
     </div>
     <div class="form-group">
       <%= f.label :price, "税抜き価格", class: "label" %>
       <%= f.text_field :price, id:"inputPrice", placeholder: "1000" %>
     </div>
     <div class="form-group">
       <%= f.radio_button :is_active, :true %>
       <%= f.label :is_active, "販売中" %><br />
       <%= f.radio_button :is_active, :false %>
       <%= f.label :is_active, "販売停止中" %><br />
     </div>
      <%= f.submit "変更を保存" , class:'btn btn-sm btn-success' %>
    <% end %>

    </div>
 </div>

</div>

app/views/admin/items/index.html.erb
<div class= "container">
  <div class = "row justify-content-between">
    <h2 class="col-4">
     商品一覧
    </h2>
    <div class ="col-2">
     <%= link_to new_admin_item_path, class:"btn btn-outline-secondary btn-block" do %>
     <i class="fa-duotone fa-plus"></i>
     <% end %>
    </div>
  </div>
  <div class= "row">
   <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 mx-auto">
      <table class="table table-hover table-inverse">
       <thead class="table-active">
        <tr>
         <th>商品ID</th>
         <th>商品名</th>
         <th colpan="2"></th>
         <th>税抜き価格</th>
         <th>ジャンル</th>
         <th>ステータス</th>
        </tr>
       </thead>
       <tbody>
        <% @items.each do |item| %>
         <tr>
          <td><%= item.id %></td>
          <td>
           <%= link_to admin_item_path(item.id) do %>
           <%= item.name %>
           <% end %>
          </td>
          <td colpan="2"></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td><%= item.is_active ? '販売中' : '販売停止中'%></td>
         </tr>
        <% end %>
       </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-sm-16 col-md-12 col-lg-10 px-10 px-sm-0">
      <h2>商品新規登録</h2>
    </div>
  </div>

  <div class= "row justify-content-center">

    <%= form_with model: @item, local: true,url: admin_items_path do |f| %>
    <!-- 追加部分 -->
     <div class="form-group row">
       <%= f.label :image, "商品画像", class: "col-sm-4 col-form-label" %>
       <!--<label for="email" class="col-sm-4 col-form-label">メールアドレス</label>-->
       <%= f.file_field :image , accept: "image/*", class: "col-md-8 form-control"%>
     </div>
     <div class="form-group row">
       <%= f.label :name, "商品名", class: "col-sm-4 col-form-label" %>
       <%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "商品名", class: "col-md-8 form-control"%>
     </div>
     <div class="form-group row">
       <%= f.label :introduction, "商品説明", class: "col-sm-4 col-form-label" %>
       <%= f.text_area :introduction, id: "inputIntroduction", placeholder: "ここに説明文を表示します", class: "col-md-8 form-control"%>
     </div>
     <div class="form-group row">
       <%= f.label :genre_id,"ジャンル選択", class: "col-sm-4 col-form-label" %>
       <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name), include_blank: "--選択してください--", class: "col-md-8 form-control"%>
       <%#= f.select :genre_id, [[@genre.name, 1], [@genre.name, 2,]], id:"genre_id",{include_blank: '--選択してください--'} %>
     </div>
     <div class="form-group row">
       <%= f.label :price, "税抜き価格", class: "col-sm-4 col-form-label" %>
       <%= f.text_field :price, id: "inputPrice", placeholder: "1000" , class: "col-md-8 form-control"%>
     </div>
     
     <div class="form-check-inline row">
       <%= f.label :price, "販売ステータス", class: "col-sm-4 col-form-label" %>
       <div class="col-md-4">
         <%= f.radio_button :is_active, :true %>
         <%= f.label :is_active, "販売中", class: "form-check-label" %>
       </div>
       <div class="col-md-4">
         <%= f.radio_button :is_active, :false %>
         <%= f.label :is_active, "販売停止中" , class: "form-check-label" %>
       </div>
     </div>
  </div>
    
     <div class="row justify-content-center">
       <%= f.submit "新規登録" , class: "btn btn-sm btn-success" %>
    <% end %>
     </div>
</div>

app/views/admin/items/show.html.erb
<div class= "container">
  <div class = "row">
    <h2 class="title">
      商品詳細
    </h2>
  </div>

  <div class= "row justify-content-center">
    <div class= "col-4">
          <p>
            <% if @item.image.attached? %>
              <%= image_tag @item.image,size: "300x300"%>
            <% else %>
              <%= image_tag 'no_image',size: "300x300"%>
            <% end %>
          </p>
    </div>
    <div class= "col-6">
      <table class= "table table table-borderless">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th><br>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th><br>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込み価格<br>(税抜き価格)</th><br>
          <td><%= @item.with_tax_price %>(<%= @item.price %>)円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <%#= form_with model: @item, local: true do |f| %>
          <td>
           <%= @item.is_active ? '販売中' : '販売停止中' %>
          </td>
          <%# end %>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_item_path(@item.id),class: "btn btn-sm btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class = "container">
  <div class = "row">
    <h2 class="title">
      注文履歴詳細
    </h2>
  </div>

  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-7 px-7 px-sm-0 mx-auto">
      <table class= "table">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_order_path(@order.id) do %>
            <%= @order.customer.last_name + @order.customer.fast_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d')%></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <%= "〒" + @order.postal_code %>
            <%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.payment_method_i18n%></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <%#= form_with model: @item, local: true do |f| %>
          <td>
           <%= @order.status_i18n %>
          </td>
          <%# end %>
          <td>
            <%= link_to "更新", admin_order_path(@order.id),class: "btn btn-sm btn-success" %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  
  <div class= "row">
    <div class="col-8">
      <table class ="table table table-bordered">
         <thead class="table-active">
          <tr>
           <th>商品名</th>
           <th colpan="3"></th>
           <th>単価(税込み)</th>
           <th>数量</th>
           <th>小計</th>
           <th>制作ステータス</th>
          </tr>
         </thead>
         <% @order.order_details.each do |order_detail| %>
         <tbody>
           <tr>
            <td><%= order_detail.item.name %></td>
            <td colpan="3"></td>
            <td><%= order_detail.price %></td>
            <td><%= order_detail.amount %>
            </td>
            <td>
              <%= order_detail.subtotal %>
            </td>
            <td><%#= order_detail.making_status_i18n %>
            </td>
           </tr>
         </tbody>
         <% end %>
        </table>
      </div>
    <div class="col-4">
      <table class ="table table table-bordered">
        <tr>
          <th>商品合計</th>
          <td><%= %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%=  %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>