config/routes.rb
Rails.application.routes.draw do


  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 # 管理者用
# URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get "about" => "homes#about", as: "about"
    resources :items, only:[:index,:show]

    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:show, :edit, :update]

    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only:[:index,:update,:create,:destroy]

    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only:[:new,:index,:show,:create]

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  namespace :admin do
    get "/" => 'homes#top'
    patch 'order_details/update'
    resources :orders, only: [:show, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :orders
  has_many :cart_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  def shipping_cost
    800
  end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid: 1, production: 2, shipping_preparation: 3, shipped: 4 }
  # { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

  private
  def order_params
    params.require(:order).permit(:id,:name,:status,:created_at,:updated_at)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item = Item.new
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
  		redirect_to admin_items_path(@item.id), notice: "商品が登録されました！"
    else
      @items = Item.all
      render :index
    end
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_items_path(@item)
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  private
  def item_params
    params.require(:item).permit(:id,:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   case resource
   when Admin
    root_path
   when Customer
    customer_path(current_customer.id)
   end
  end

  private


  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:last_name,:fast_name,
   :last_name_kana,:fast_name_kana,:postal_code,:address,:telephone_number,:is_deleted,
   :created_at,:updated_at])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/making_status_helper.rb
module Admin::MakingStatusHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/status_helper.rb
module Admin::StatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/39d93930e2.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <header class="shadow-sm pt-5 pb-4">
      <nav class="navbar navbar-expand-lg navbar-light">
       <div class="container">
        <a class="navbar-brand p-3" href="/">
          <span>Logo</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <!--navbar-toggler ナビゲーションアイコン（ハンバーガーメニュー）の枠部分-->

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ml-auto">

          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_items_path, class: 'nav-link text-black' do %>
            商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_customers_path, class: 'nav-link text-black' do %>
            会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_path, class: 'nav-link text-black' do %>
            注文履歴一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_genres_path, class: 'nav-link text-black' do %>
            ジャンル一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-black' do %>
            ログアウト
            <% end %>
          </li>

        <% elsif customer_signed_in? %>
          <li class="nav-item">
            <%= link_to customer_path(current_customer.id), class: 'nav-link text-black' do %>
            マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: 'nav-link text-black' do %>
            商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to cart_items_path, class: 'nav-link text-black' do %>
            カート
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-black' do %>
            ログアウト
            <% end %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to about_path, class: 'nav-link text-black' do %>
             About
            <% end %>
            </li>
          <li class="nav-item">
            <%= link_to new_customer_registration_path, class: 'nav-link text-black' do %>
            新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: 'nav-link text-black' do %>
            商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_session_path, class: 'nav-link text-black' do %>
             ログイン
            <% end %>
          </li>
        <% end %>

        </ul>
       </div>
      </div>
     </nav>
    </header>

    <main class="mb-auto">

    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
        </div>
      </div>
    </footer>
  </body>
</html>